Make ps2epsi create a temporary file more securely in an owner-locked directory. Closes bug #687243.
git-svn-id: http://svn.ghostscript.com/ghostscript/trunk@6505 a1074d23-0009-0410-80fe-cf8c14f379e6

diff --git a/gs/lib/ps2epsi b/gs/lib/ps2epsi
--- a/gs/lib/ps2epsi
+++ b/gs/lib/ps2epsi
@@ -5,7 +5,14 @@
 # executable name set in the makefile
 GS_EXECUTABLE=gs
 
-tmpfile=/tmp/ps2epsi$$
+# try to create a temporary file securely
+tmpdir=/tmp/ps2epsi.$$
+(umask 077 && mkdir $tmpdir)
+if ! test -d $tmpdir; then
+	echo "failed: could not create temporary file"
+	exit 1
+fi
+tmpfile=$tmpdir/ps2epsi$$
 
 export outfile
 
@@ -57,6 +64,7 @@ awk 'F==1	{
 
 $GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
 rm -f $tmpfile
+rm -rf $tmpdir
 
 (
 cat << BEGINEPS
