Merge the gs853merge branch down into the trunk. This ports ghostpcl and ghostxps to build against a branch of ghostscript close it its current mainline (around r7000) between Ghostscript 8.54 and 8.55.
This mostly consists of removing the memory pointers from many calls as
well as a few other api changes, as well as some makefile updates, which
were skewed between the branches.

Nevertheless this is a big merge and there are likely to be a few
mistakes. The previous trunk is tagged as /tags/ghostpcl-pre855merge
for comparision.

Both pcl6 and pspcl6 build and run with the Artifex font scaler (the
native gs one). pcl6 compiles but does not link with ufst. pspcl6 does
not compile with ufst, but that's not too different from what was
happening in the branch. Fixing this will of course come next.

git-svn-id: http://svn.ghostscript.com/ghostpcl/trunk/ghostpcl@2566 06663e23-700e-0410-b217-a244a6096597

diff --git a/gs/lib/ps2epsi b/gs/lib/ps2epsi
--- a/gs/lib/ps2epsi
+++ b/gs/lib/ps2epsi
@@ -1,7 +1,18 @@
 #!/bin/sh
-# $RCSfile$ $Revision$
+# $Id$
 
-tmpfile=/tmp/ps2epsi$$
+# This definition is changed on install to match the
+# executable name set in the makefile
+GS_EXECUTABLE=gs
+
+# try to create a temporary file securely
+tmpdir=/tmp/ps2epsi.$$
+(umask 077 && mkdir $tmpdir)
+if test ! -d $tmpdir; then
+	echo "failed: could not create temporary file"
+	exit 1
+fi
+tmpfile=$tmpdir/ps2epsi$$
 
 export outfile
 
@@ -51,8 +62,9 @@ awk 'F==1	{
 		}
 	' U="$USERNAME$LOGNAME"  F=1 - F=2 "${infile}" >$tmpfile
 
-gs -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
+$GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
 rm -f $tmpfile
+rm -rf $tmpdir
 
 (
 cat << BEGINEPS
@@ -62,8 +74,8 @@ save countdictstack mark newpath /showpage {} def /setpagedevice {pop} def
 BEGINEPS
 
 cat "${infile}" |
-sed -e '/^%%BeginPreview:/,/^%%EndPreview[^!-~]*$/d' -e '/^%!PS-Adobe/d'\
-	-e '/^%%[A-Za-z][A-Za-z]*[^!-~]*$/d' -e '/^%%[A-Za-z][A-Za-z]*: /d'
+sed -e '/^%%BeginPreview:/,/^%%EndPreview[^!-\~]*$/d' -e '/^%!PS-Adobe/d'\
+	-e '/^%%[A-Za-z][A-Za-z]*[^!-\~]*$/d' -e '/^%%[A-Za-z][A-Za-z]*: /d'
 
 cat << ENDEPS
 %%Trailer
