Use mktemp in ps2epsi, bug 689324.
git-svn-id: http://svn.ghostscript.com/ghostscript/trunk@8103 a1074d23-0009-0410-80fe-cf8c14f379e6

diff --git a/gs/lib/ps2epsi b/gs/lib/ps2epsi
--- a/gs/lib/ps2epsi
+++ b/gs/lib/ps2epsi
@@ -6,13 +6,21 @@
 GS_EXECUTABLE=gs
 
 # try to create a temporary file securely
-tmpdir=/tmp/ps2epsi.$$
-(umask 077 && mkdir $tmpdir)
-if test ! -d $tmpdir; then
-	echo "failed: could not create temporary file"
-	exit 1
+if test -z "$TMPDIR"; then
+	TMPDIR=/tmp
 fi
-tmpfile=$tmpdir/ps2epsi$$
+if which mktemp >/dev/null 2>/dev/null; then
+	tmpfile="`mktemp $TMPDIR/ps2epsi.XXXXXX`"
+else
+	tmpdir=$TMPDIR/ps2epsi.$$
+	(umask 077 && mkdir "$tmpdir")
+	if test ! -d "$tmpdir"; then
+		echo "failed: could not create temporary file"
+		exit 1
+	fi
+	tmpfile="$tmpdir"/ps2epsi$$
+fi
+trap "rm -rf \"$tmpfile\"" 0 1 2 3 7 13 15
 
 export outfile
 
@@ -60,11 +68,11 @@ awk 'F==1	{
 		print "end";
 		exit(0);
 		}
-	' U="$USERNAME$LOGNAME"  F=1 - F=2 "${infile}" >$tmpfile
+	' U="$USERNAME$LOGNAME"  F=1 - F=2 "${infile}" >"$tmpfile"
 
-$GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
-rm -f $tmpfile
-rm -rf $tmpdir
+$GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null "$tmpfile" ps2epsi.ps "$tmpfile" <"${infile}" 1>&2
+rm -f "$tmpfile"
+rm -rf "$tmpdir"
 
 (
 cat << BEGINEPS
